### ISSUE TITLE
IQsharp Kernel Fails to connect in Jupyter Notebook. 

### ISSUE THREAD

**Issue by U695** [microsoft/iqsharp#494] opened 2021-08-11 04:32 UTC
Short description:

I have followed the instructions provided https://docs.microsoft.com/en-us/azure/quantum/install-jupyter-qdk?tabs=tabid-conda and am onto the part where I am told to copy and past the operation function  'SampleQuantumRandomNumberGenerator' and run it in a cell. 

Upon opening up a Q# Notebook in Jupyter Notebook, I am unable to run any cells although the kernel is said to be connected. 
After a short while the Conda Terminal running the qsharp-env outputs nudges then a tornado timeout whilst simultaneously the notebook tries to reconnect to the kernel without success.

Output in Conda Prompt (Run as Admin):
![image](https://user-images.githubusercontent.com/88758923/128969870-3fad6337-a56d-4fd1-8cfd-b91957dc864b.png)

Rather than reiterating, the symptoms I am experiencing are exactly the same as described in a past post: https://github.com/microsoft/iqsharp/issues/387

**Comment by anjbur** [comment] 2021-08-12 17:34
Thank you for reporting this issue! I'll investigate the error and will update this thread.

**Comment by anjbur** [comment] 2021-08-19 00:23
@U695 @lfenster could you re-run the command with debug logging enabled on IQ# and jupyter? We haven't been able to reproduce it locally and seeing additional logs would be very helpful. You can enable debug logging on IQ# with the conda command `conda env config vars set IQSHARP_LOG_LEVEL=Debug` and on jupyter by adding a --debug flag 
(i.e. `jupyter notebook --debug`). Thank you!

**Comment by U695** [comment] 2021-08-22 08:14
Here is the terminal output with the debug settings you recommended.
![image](https://user-images.githubusercontent.com/88758923/130347492-014b56de-ccdc-4b9e-9eb7-98a262e584e3.png)

![image](https://user-images.githubusercontent.com/88758923/130347474-46cc8021-c746-43e8-a66a-362757758137.png)

**Comment by cgranade** [comment] 2021-08-23 18:02
Thanks for sharing, @U695! Two things jump out at me: no debug logs were printed by IQ# at all, and it looks like you have version 0.13.20111004 of IQ# instead of the latest 0.18.2107153439. If you installed via conda, I'm guessing you hit #500, as that could cause an old version of IQ# to get installed when using conda environments based on Python 3.8 or 3.9. We have a potential fix in progress at #501, but in the meantime, would you be willing to try using a Python 3.7 environment as a workaround? Thank you for your help and for reporting this issue!

**Comment by lfenster** [comment] 2021-08-23 20:54
@cgranade, are the versions of iq# and the vscode qdk the same? I ask because I think I have python 3.7 (thats what i shows me), i followed the instructions and installed the vscode qdk as well and it shows the current version as 0.18.2107153439.  However, like @U695, i hit this issue with jupyter and when i look at the debug output, I am also seeing _Received kernel info: {'protocol_version': '5.2.0', 'implementation': 'iqsharp', 'implementation_version': '0.13.20111004', 'language_info': {'name': 'qsharp', 'version': '0.12', 'mimetype': 'text/x-qsharp', 'file_extension': '.qs'}, 'banner': None, 'help_links': None}_

**Comment by cgranade** [comment] 2021-08-23 21:14
> @cgranade, are the versions of iq# and the vscode qdk the same?

Not necessarily, no. The VS Code extension and IQ# versions are managed separately, such that you can have a different version of each, or even a different version of IQ# in two different conda environments.

> I ask because I think I have python 3.7 (thats what i shows me), i followed the instructions and installed the vscode qdk as well and it shows the current version as 0.18.2107153439. However, like @U695, i hit this issue with jupyter and when i look at the debug output, I am also seeing _Received kernel info: {'protocol_version': '5.2.0', 'implementation': 'iqsharp', 'implementation_version': '0.13.20111004', 'language_info': {'name': 'qsharp', 'version': '0.12', 'mimetype': 'text/x-qsharp', 'file_extension': '.qs'}, 'banner': None, 'help_links': None}_

Ah, that's interesting, it sounds like you also got a downgraded version somehow... Hopefully, that should get fixed with #501 as well, but to confirm, would you be willing to share the output of `conda env export` so that I can look at what package may be causing the downgrade? Thank you!

> Also, if it helps, here's the debug output in between "Nudge" attempts (I can include more output if desired):
> [_D 11:29:30.153 NotebookApp] Nudge: attempt 1 on kernel 75f2324e-0381-4da9-8fbc-815959d5cc6f dbug: Microsoft.Jupyter.Core.ShellServer[0] Received new message: {"msg_id":"dd9da9bd4ecc485fa403d0bac5f4ee9c_1","username":"username","session":"dd9da9bd4ecc485fa403d0bac5f4ee9c","msg_type":"kernel_info_request","version":"5.3"} {"msg_id":"336aaa98-8950-4ee9-b972-5d56019e79cb","username":"lfenster","session":null,"msg_type":null,"version":"5.2.0"} {} {} [D 11:29:30.162 NotebookApp] Nudge: shell info reply received: 75f2324e-0381-4da9-8fbc-815959d5cc6f [D 11:29:30.168 NotebookApp] Nudge: resolving shell future: 75f2324e-0381-4da9-8fbc-815959d5cc6f dbug: Microsoft.Jupyter.Core.ShellRouter[0] Handling message of type kernel_info_request. dbug: Microsoft.Jupyter.Core.ShellServer[0] Sending shell message: {"ZmqIdentities":["AJJaZTg="],"Signature":null,"Header":{"msg_id":"d7436264-08e6-4b7b-9b54-5cb31a8bc04d","username":"lfenster","session":"dd9da9bd4ecc485fa403d0bac5f4ee9c","msg_type":"kernel_info_reply","version":"5.2.0"},"ParentHeader":{"msg_id":"dd9da9bd4ecc485fa403d0bac5f4ee9c_1","username":"username","session":"dd9da9bd4ecc485fa403d0bac5f4ee9c","msg_type":"kernel_info_request","version":"5.3"},"Metadata":null,"Content":{"protocol_version":"5.2.0","implementation":"iqsharp","implementation_version":"0.13.20111004","language_info":{"name":"qsharp","version":"0.12","mimetype":"text/x-qsharp","file_extension":".qs"},"banner":null,"help_links":null}}_

That makes sense; there was a bug back with 0.13 that would cause the kernel to not respond to startup messages correctly in some circumstances, such that debug log matches what I would expect given the downgrade. Thank you for sharing those details!

**Comment by lfenster** [comment] 2021-08-24 17:18
you were right.  when i went to provide the output for conda env export, it became very clear to me that it is python 3.8.  So I guess I am a victim of https://github.com/microsoft/iqsharp/issues/500? :-(

**Comment by cgranade** [comment] 2021-08-24 18:09
@lfenster: Thanks for checking on that, does sound like #500 is the root cause in this case as well, then. Our goal is to have that fixed fairly soon, but in the meantime you should be able to use Python 3.7 in a new conda environment as a workaround:

```
conda create -n py37-qsharp -c quantum-engineering notebook qsharp python=3.7
```

**Comment by lfenster** [comment] 2021-08-24 19:01
Okay.  I'll try that.  I wouldnt have thought that would have made a difference since I followed the instructions to run this in the qsharp-env that is described and I think its using pyth3.7 in that environment already.  so, when I do `conda activate qsharp-env` and then follow it with `conda env export`, I see only 37.  export below:


name: qsharp-env
channels:
  - quantum-engineering
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37h2bbff1b_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.weakref=1.0.post1=py_1
  - bleach=4.0.0=pyhd3eb1b0_0
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py37haa95532_0
  - cffi=1.14.6=py37h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - importlib-metadata=3.10.0=py37haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.26.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - iqsharp=0.13.2011.1004=py37_0
  - jedi=0.18.0=py37haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py37h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37hfa6e2cd_1001
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.2=py37haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py37haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py37haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py37he774522_0
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=228=py37hbaba5e8_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=22.2.1=py37hd77b12b_1
  - qsharp=0.13.2011.1004=py37_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - terminado=0.9.4=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.0=pyhd3eb1b0_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - zipp=3.5.0=pyhd3eb1b0_0
  - pip:
    - azure-quantum==0.13.2011.1004
    - qsharp-chemistry==0.13.2011.1004
    - qsharp-core==0.13.2011.1004
variables:
  IQSHARP_LOG_LEVEL: Debug
prefix: C:\ProgramData\Anaconda3\envs\qsharp-env

**Comment by cgranade** [comment] 2021-08-24 20:32
Thanks for sharing, @lfenser! From that listing, it seems that the versions of `jupyter_client`, `pyzmq`, and `notebook` are all more recent than was allowed by `qsharp` versions 0.14 through 0.18. We locked those versions down to work around a bug in `pyzmq` 20.0.0 that has since been fixed in upstream. If I explicitly tell `conda` that I want an environment with the latest version of the `qsharp` conda package, it looks like it picks out different versions for each of these dependencies:

```
PS>  conda create -n iqsharp-494 -c quantum-engineering qsharp>=0.18.2107.153439
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\cgran\Anaconda3\envs\iqsharp-494

  added / updated specs:
    - qsharp[version='>=0.18.2107.153439']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-21.2.2                 |   py37haa95532_0         1.8 MB
    python-3.7.11              |       h6244533_0        14.5 MB
    pywin32-228                |   py37hbaba5e8_1         5.6 MB
    ------------------------------------------------------------
                                           Total:        21.9 MB

The following NEW packages will be INSTALLED:

  backports          pkgs/main/noarch::backports-1.0-pyhd3eb1b0_2
  backports.weakref  pkgs/main/noarch::backports.weakref-1.0.post1-py_1
  ca-certificates    pkgs/main/win-64::ca-certificates-2021.7.5-haa95532_1
  certifi            pkgs/main/win-64::certifi-2021.5.30-py37haa95532_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  iqsharp            quantum-engineering/win-64::iqsharp-0.18.2107.153439-py37_0
  jupyter_client     pkgs/main/noarch::jupyter_client-6.1.12-pyhd3eb1b0_0
  jupyter_core       pkgs/main/win-64::jupyter_core-4.7.1-py37haa95532_0
  libsodium          pkgs/main/win-64::libsodium-1.0.18-h62dcd97_0
  openssl            pkgs/main/win-64::openssl-1.1.1k-h2bbff1b_0
  pip                pkgs/main/win-64::pip-21.2.2-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.11-h6244533_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0
  pywin32            pkgs/main/win-64::pywin32-228-py37hbaba5e8_1
  pyzmq              pkgs/main/win-64::pyzmq-19.0.2-py37ha925a31_1
  qsharp             quantum-engineering/win-64::qsharp-0.18.2107.153439-py37_0
  setuptools         pkgs/main/win-64::setuptools-52.0.0-py37haa95532_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
  sqlite             pkgs/main/win-64::sqlite-3.36.0-h2bbff1b_0
  tornado            pkgs/main/win-64::tornado-6.1-py37h2bbff1b_0
  traitlets          pkgs/main/noarch::traitlets-5.0.5-pyhd3eb1b0_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.0-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zeromq             pkgs/main/win-64::zeromq-4.3.2-ha925a31_3
```

Hopefully this workaround shouldn't be needed soon, but in the meantime specifying `qsharp>=0.18.2107.153439` instead should force `conda` to either get the right version or fail with package conflicts.

**Comment by lfenster** [comment] 2021-08-24 21:15
thanks for this, @cgranade!  Given your direction, I created the same environment using `conda create -n iqsharp-494 -c quantum-engineering qsharp>=0.18.2107.153439`.  I then activated it (`conda activate iqsharp-494`) and tested it with `jupyter notebook --debug`.  Got message that it couldnt detect the kernel though.  For options to set kernel, only python3 was listed; q# was not a choice.  Did I miss something or mess something up?

**Comment by anjbur** [comment] 2021-08-24 23:54
@lfenster I was able to reproduce your issue using the command you listed, and resolved it by adding the qsharp and notebook channels to the conda environment! To create environment: `conda create -n 494-test -c quantum-engineering qsharp notebook qsharp>=0.18.2107.153439`

**Comment by lfenster** [comment] 2021-08-25 04:06
Success!!! Huge thanks to you, @anjbur  and @cgranade for helping me to get this working!!

**Closed** 2021-08-31 04:28 UTC
Labels: Kind-Bug, Area-Kernel

**Comment by jagumiel** [comment] 2021-12-01 10:52
I am facing the same problem on Linux. I am using venv. How can I fix this problem?

Thanks in advance.

**Comment by cgranade** [comment] 2021-12-01 17:55
@jagumiel: To confirm that this is the same bug and not a new issue, would you be willing to share the exact error message that you've run into, the output of `pip list`, and the output of `dotnet iqsharp --version`? Thanks!
