### ISSUE TITLE
"Q# environment was not available in allocated time." when importing qsharp

### ISSUE THREAD

**Issue by cqc-alec** [microsoft/iqsharp#488] opened 2021-07-26 08:15 UTC
Running `python -c "import qsharp"` gives the following error after a wait of several seconds:
```
Preparing Q# environment...
...................Q# environment was not available in allocated time.
Please check the instructions at https://aka.ms/qdk-install/python.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[...]/lib/python3.8/site-packages/qsharp/__init__.py", line 123, in <module>
    client = _start_client()
  File "[...]/lib/python3.8/site-packages/qsharp/clients/__init__.py", line 64, in _start_client
    raise IQSharpNotAvailableError(message)
qsharp.clients.IQSharpNotAvailableError: Q# environment was not available in allocated time.
Please check the instructions at https://aka.ms/qdk-install/python.
```

 - OS: Linux (Ubuntu 20.04, x86_64)
 - Versions: Python 3.8.10, qsharp 0.18.2106.148911
 
```
$ dotnet iqsharp --version
iqsharp: 0.18.2106148911
Jupyter Core: 1.5.0.0
.NET Runtime: .NETCoreApp,Version=v3.1
```

**Comment by anjbur** [comment] 2021-07-27 01:47
Hi! Thank you for reporting the issue. Could you set the environment variable IQSHARP_LOG_LEVEL to Debug (if you're using conda, `conda env config vars set IQSHARP_LOG_LEVEL=Debug` and then reactivate the environment), re-run the command, and post the resulting logs here? That would be a big help in debugging this issue, as I haven't been able to reproduce it on my end. Thank you!

**Comment by cqc-alec** [comment] 2021-07-27 05:45
Sure, I have run the command again with `IQSHARP_LOG_LEVEL=Debug` and attach the output below.

[qsharp-errors.txt](https://github.com/microsoft/iqsharp/files/6882979/qsharp-errors.txt)

**Comment by cqc-alec** [comment] 2021-07-27 05:53
Could it be this?
```
Microsoft.Quantum.IQSharp.NugetPackages[0]
      One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Microsoft.Quantum.Standard 0.18.2106148911 constraint: Microsoft.Quantum.Runtime.Core (>= 0.18.2106148911)', 'Microsoft.Quantum.Standard 0.18.2106148911 constraint: Microsoft.Quantum.QSharp.Core (>= 0.18.2106148911)', 'Microsoft.Quantum.Standard 0.18.2106148911 constraint: Microsoft.Quantum.Simulators (>= 0.18.2106148911)', 'Microsoft.Quantum.Standard 0.18.2106148911 constraint: NumSharp (>= 0.20.5)'
```

**Comment by anjbur** [comment] 2021-07-28 19:35
@cqc-alec Thank you for sharing the logs! I don't think the NuGet warning is the issue, as I get the same warning on my machine where the import works. I haven't been able to reproduce the error, but I might know what's going on. No information is showing in the logs about the version of the `qsharp` python package you have installed. Could you verify what version you have? It looks like you did the installation through pip and .NET CLI rather than conda, is that correct?

I suspect your `qsharp` package version is 0.17.2105.144881 or lower. If that's the case, the issue should resolve if you update the package. There was a change made to the messaging between the IQ# kernel and Python in #378 and #457 that should be backwards compatible, but because your `qsharp` version information isn't available the new messaging format is being defaulted to.

**Comment by cqc-alec** [comment] 2021-07-28 19:50
Hi @anjbur -- I installed `qsharp` with `pip`, and have the following version:
```
$ pip show qsharp
Name: qsharp
Version: 0.18.2106.148911
```
But, I just checked my version of `qsharp-core`, and it was `0.17.2105.144881`. After doing `pip install -U qsharp-core`, this upgraded to `0.18.2107.153439`, and the issue went away!

So it seems that `qsharp-core` was not automatically upgraded when I last upgraded `qsharp`. Perhaps `qsharp` should require a minimum version of `qsharp-core`?

Thanks for your help!

**Comment by cgranade** [comment] 2021-08-04 16:40
Thanks for the suggestion, @cqc-alec! We're tracking the work to lock `qsharp` and `qsharp-core` versions to each other at https://github.com/microsoft/QuantumLibraries/pull/468.

**Comment by cqc-alec** [comment] 2021-08-16 07:18
OK thank you @cgranade ! Happy for this to be closed then unless you would like to keep it open.

**Comment by cgranade** [comment] 2021-08-16 15:39
@cqc-alec: Thanks! If it's alright, going to close this now, then, since https://github.com/microsoft/QuantumLibraries/pull/468 has been merged in. Starting with the next release, the versions of the `qsharp` metapackage and the `qsharp-core` package should be locked to each other, such that this issue should not occur in the future. Please feel free to reopen or open a new issue and let us know if it does re-occur, or if something else goes wrong. Thanks again!

**Closed by cgranade** 2021-08-16 15:39 UTC
Labels: Kind-Bug, Area-Python
