### ISSUE TITLE
Unable to install iqsharp OSX

### ISSUE THREAD

**Issue by sid137** [microsoft/iqsharp#116] opened 2020-04-11 00:43 UTC
Hi,

I'm getting the following error when trying to install iqsharp on OX

```
:~/quantum/qs $ dotnet iqsharp install
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Jupyter.Core.KernelApplication..ctor(KernelProperties properties, Action`1 configure)
   at Microsoft.Quantum.IQSharp.Jupyter.IQSharpKernelApp..ctor(KernelProperties properties, Action`1 configure) in D:\a\1\s\submodules\iqsharp\src\Jupyter\KernelApp\IQSharpKernelApp.cs:line 15
   at Microsoft.Quantum.IQSharp.Program.Main(String[] args) in D:\a\1\s\submodules\iqsharp\src\Tool\Program.cs:line 68
```

**To Reproduce**
1. Using system python
2. Install dotnet core using Homebrew cask `brew cask install dotnet-sdk`
3. Install sharp `pip install qsharp`
4. Begin iqsharp installation `dotnet tool install -g Microsoft.Quantum.IQSharp`
5. Error here `dotnet iqsharp install`

As per the instructions here:  https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

**System information**
Python 3.7.2 (default, Jan 13 2019, 12:50:01)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
DotNet Core SDK Version: 3.1.201
OS: OSX Catalina 10.15.4 (19E266)
PATH="$PATH:/Users/myuser/.dotnet/tools"

Tool 'microsoft.quantum.iqsharp' was reinstalled with the latest stable version (version '0.11.2003.3107').

**Comment by anpaz-msft** [comment] 2020-04-20 18:36
hi @sid137, I haven't been able to reproduce.
`dotnet iqsharp install` could fail if jupyter is not installed; doing `pip install qsharp` should take care of that.
could you do a `pip freeze | grep jupyter` and confirm it is installed?

**Comment by sid137** [comment] 2020-04-20 18:47
hi @anpaz-msft 

I just verified that jupyter is installed:

`:~ $ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3`

I also tried to completely remove iqsharp and reinstall from scratch, no go:

`:~ $ pip uninstall qsharp
Found existing installation: qsharp 0.11.2003.3107
Uninstalling qsharp-0.11.2003.3107:
  Would remove:
    /usr/local/lib/python3.7/site-packages/qsharp-0.11.2003.3107.dist-info/*
    /usr/local/lib/python3.7/site-packages/qsharp/*
Proceed (y/n)? y
  Successfully uninstalled qsharp-0.11.2003.3107
:~ $ dotnet tool uninstall -g Microsoft.Quantum.IQSharp
Tool 'microsoft.quantum.iqsharp' (version '0.11.2003.3107') was successfully uninstalled.
:~ $ pip install qsharp
`

 Reinstalling after uninstall:

`:~ $ pip install qsharp
Collecting qsharp
  Using cached qsharp-0.11.2003.3107-py3-none-any.whl (18 kB)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/site-packages (from qsharp) (6.1.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client->qsharp) (2.7.5)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/site-packages (from jupyter-client->qsharp) (19.0.0)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/site-packages (from jupyter-client->qsharp) (4.6.3)
Requirement already satisfied: tornado>=4.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client->qsharp) (6.0.4)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/site-packages (from jupyter-client->qsharp) (4.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.1->jupyter-client->qsharp) (1.11.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/site-packages (from traitlets->jupyter-client->qsharp) (4.3.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/site-packages (from traitlets->jupyter-client->qsharp) (0.2.0)
Installing collected packages: qsharp
Successfully installed qsharp-0.11.2003.3107
:~ $ dotnet tool install -g Microsoft.Quantum.IQSharp
You can invoke the tool using the following command: dotnet-iqsharp
Tool 'microsoft.quantum.iqsharp' (version '0.11.2003.3107') was successfully installed.

:~ $ dotnet iqsharp install
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Jupyter.Core.KernelApplication..ctor(KernelProperties properties, Action`1 configure)
   at Microsoft.Quantum.IQSharp.Jupyter.IQSharpKernelApp..ctor(KernelProperties properties, Action`1 configure) in D:\a\1\s\submodules\iqsharp\src\Jupyter\KernelApp\IQSharpKernelApp.cs:line 15
   at Microsoft.Quantum.IQSharp.Program.Main(String[] args) in D:\a\1\s\submodules\iqsharp\src\Tool\Program.cs:line 68`


Screen recording:
https://share.getcloudapp.com/Jrubw5Y1


Is there anything else I can provide to help debug?

**Comment by rmshaffer** [comment] 2020-07-02 16:50
@sid137 apologies for the lack of response on this. As an update on this issue, we have just released conda packages for Windows, Mac, and Linux that should make installation of iqsharp less error-prone. If you'd like to try it out, please check the instructions at https://docs.microsoft.com/en-us/quantum/quickstarts/install-python.

**Comment by rmshaffer** [comment] 2020-07-07 18:24
Closing this issue since we haven't yet been able to reproduce it, and since the conda package is now the recommended IQ# installation path and should avoid environment-specific issues like this.

**Closed by rmshaffer** 2020-07-07 18:24 UTC
Labels: Area-Install, bug
