### ISSUE TITLE
Installing MS QDK to run Q# with python on Ubuntu 18 — “dotnet iqsharp install” step fails

### ISSUE THREAD

**Issue by swernli** [microsoft/iqsharp#102] opened 2020-03-09 19:22 UTC
Copied from a [StackOverflow question](https://stackoverflow.com/questions/60593638/installing-ms-qdk-to-run-q-with-python-on-ubuntu-18-dotnet-iqsharp-install?newreg=9c6c33dc21f541e98aac2280569562dd).

Here's the original question and repro steps:

Using the instructions in https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

I get following:

dotnet iqsharp install

It was not possible to find any compatible framework version The framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found. - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at: - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.0.0&arch=x64&rid=ubuntu.18.04-x64

It seems you cannot get AspNetCore.App 3.0.0 anymore but I have 3.0.3 installed - See below here for my setup .....
dotnet --info

.NET Core SDK (reflecting any global.json): Version: 3.1.102 Commit: 573d158fea

Runtime Environment: OS Name: ubuntu OS Version: 18.04 OS Platform: Linux RID: ubuntu.18.04-x64 Base Path: /usr/share/dotnet/sdk/3.1.102/

Host (useful for support): Version: 3.1.2 Commit: 916b5cba26

.NET Core SDKs installed:

3.0.103 [/usr/share/dotnet/sdk]

3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:

Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App] Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App] Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App] Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs: https://aka.ms/dotnet-download

PATH=/home/dramsay/Qcomp-env/bin:/home/dramsay/bin:/home/dramsay/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dramsay/.dotnet/tools:/snap/dotnet-sdk/63/host/fxr/3.1.2:/snap/dotnet-sdk/63/sdk:/snap/dotnet-sdk/63/host/fxr/3.1.2:/usr/share/dotnet/shared/Microsoft.AspNetCore.App:/usr/share/dotnet/shared/Microsoft.NETCore.App

Thanks in advance for any pointers

**Comment by swernli** [comment] 2020-03-09 19:25
I was able to repro a similar issue in a Windows container that has pyther, jupyter, and .NET Core SDK 3.1 installed:
```
C:\>dotnet iqsharp install
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\ContainerAdministrator\.dotnet\tools\.st
ore\microsoft.quantum.iqsharp\0.10.2002.2610\microsoft.quantum.iqsharp\0.10.2002.2610\tools\netcoreapp3.0\any\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or us
e the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWAR
E\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
```
It appears from the error above that the tool is failing because it's trying to find .NET core 3.0. There are still several references in the projects here to `netcoreapp3.0` which should be updated to `netcoreapp3.1`, as well as references to Microsoft.NETCore.App 3.0.0, which would probably explain the issues the original poster asked. These should be updated to latest and/more flexible references.

**Comment by cgranade** [comment] 2020-03-09 19:55
> I was able to repro a similar issue in a Windows container that has pyther, jupyter, and .NET Core SDK 3.1 installed:
> 
> ```
> C:\>dotnet iqsharp install
> A fatal error occurred. The required library hostfxr.dll could not be found.
> If this is a self-contained application, that library should exist in [C:\Users\ContainerAdministrator\.dotnet\tools\.st
> ore\microsoft.quantum.iqsharp\0.10.2002.2610\microsoft.quantum.iqsharp\0.10.2002.2610\tools\netcoreapp3.0\any\].
> If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or us
> e the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWAR
> E\dotnet\Setup\InstalledVersions\x64\InstallLocation].
> 
> The .NET Core runtime can be found at:
>   - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
> ```
> 
This looks like a different error than was reported on the Linux container, originating from missing a `DOTNET_ROOT` environment variable? Are you able to install and run any .NET Core Global Tools (I always find `dotnet-say`, `dotnet-format`, and `dotnet-suggest` to be reasonable test cases) from your Windows container?

**Comment by swernli** [comment] 2020-03-09 20:02
Ah, I think you are right; I get the same error dotnet-say. So my environment is not well configured.
That said, I do think updating netcoreapp references and removing the version from the AspNetCoreApp (per the recommendation [here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendation) ) are probably the right thing to do in general. I don't know that it will resolve the issue the SO question points to.

**Comment by cgranade** [comment] 2020-03-09 20:08
I agree, it would be good to follow that recommendation regardless of whether or not it's the root cause of this particular issue. In particular, making a PR with that change would let us get a complete beta build that we could use to try and reproduce the issue as a part of that root cause analysis; would you want to go on and make that a PR with that change, then?

**Comment by swernli** [comment] 2020-03-09 20:09
Yes, I can go ahead and do that update. Thanks for the pointer on DOTNET_ROOT, as that seems to have resolved the issue in my container:
```
C:\>set DOTNET_ROOT=C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\

C:\>dotnet iqsharp install
[InstallKernelSpec] Installed kernelspec iqsharp in C:\ProgramData\jupyter\kernels\iqsharp
```

**Comment by dra42841** [comment] 2020-03-12 04:29
Stefan - was just wondering if some sort of "green light" appears in Stackoverflow (or here) that the changes you speak of have been implemented and then I can re-do all the install steps ?

**Comment by swernli** [comment] 2020-03-12 17:45
@cgranade Might have a better answer... I believe that you'll have to wait for the next monthly release, but he can correct me if there is another way to try this out on your system sooner.

**Comment by cgranade** [comment] 2020-03-12 17:48
As @swernli notes, we release each month rolling up the fixes and changes from the previous month. In the meantime, you can use the versions in our prerelease feed at https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_packaging. I think 0.10.2003.1102-beta should have what you need, but have not yet confirmed that, sorry.

**Comment by dra42841** [comment] 2020-03-13 04:18
Thanks Stefan and Chris for the update - I didn't know about the monthly releases - beta (excuse the pun) to wait for the monthly rel I think

**Comment by rmshaffer** [comment] 2020-06-04 18:03
@dra42841, have you had a chance to try this out using one of the recent releases? Any of the releases since March should have the necessary update. https://docs.microsoft.com/en-us/quantum/relnotes/

**Comment by rmshaffer** [comment] 2020-06-04 20:17
Closing this because we believe it is resolved in current releases, but please re-open this or open a new issue if you are experiencing any more issues!

**Closed by rmshaffer** 2020-06-04 20:17 UTC
Labels: Area-Install, bug
