### ISSUE TITLE
Exception: Q# environment was not available in allocated time.

### ISSUE THREAD

**Issue by shadab-entrepreneur** [microsoft/iqsharp#407] opened 2021-02-08 04:47 UTC
I'm trying to deploy a web-app on Heroku using the docker image. But getting the below error:
```
AttributeError: module 'qsharp' has no attribute 'clients'
Traceback:
File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "/app/qrng_final.py", line 18, in <module>
    import qsharp
File "/usr/local/lib/python3.7/site-packages/qsharp/__init__.py", line 123, in <module>
    client = _start_client()
File "/usr/local/lib/python3.7/site-packages/qsharp/clients/__init__.py", line 31, in _start_client
    client = qsharp.clients.iqsharp.IQSharpClient()
```

Docker file for reference- [Dockerfile](https://github.com/shadab-entrepreneur/Quantum-Random-Number-Generator-using-Streamlit/blob/main/Dockerfile)
Code Repo- [QRNG using Streamlit](https://github.com/shadab-entrepreneur/Quantum-Random-Number-Generator-using-Streamlit/)

Screenshot of logs for reference:
![Screenshot 2021-02-08 at 10 35 58 AM](https://user-images.githubusercontent.com/10863620/107178167-9905cf00-69f9-11eb-8694-b730440bfe5c.png)

Any idea how to resolve this?

**Comment by cgranade** [comment] 2021-02-08 05:16
It looks like this may be an example of https://github.com/microsoft/iqsharp/issues/387, but that should have been fixed with January's release of IQ#. Looking at your Dockerfile, when you use `latest`, Docker can sometimes cache older versions which can cause this kind of problem. I'd suggest putting an explicit version of `iqsharp-base` in your `FROM` line.

BTW, this is likely not the cause of the issue, but it does look like your Dockerfile overwrites the installation of the `qsharp`, `qsharp-core`, and `qsharp-chemistry` packages with the `RUN pip install -r requirements.txt` line. In particular, the versions of the packages that are installed with that line may conflict with the version of the IQ# kernel brought in from your `FROM` line.

**Comment by shadab-entrepreneur** [comment] 2021-02-10 04:06
I tried putting explicit version also for `iqsharp-base` and removed packages related to `qsharp` from `requirements.txt` file but still its not getting connected. Is there any way to access IQ# kernel directly via python installed?

**Comment by anjbur** [comment] 2021-03-09 00:51
@shadab-entrepreneur Do you still get the same error with the explicit version for `iqsharp-base` or something different?

Also, while this is unlikely to be the issue, taking a quick look at your Dockerfile it shouldn't be necessary to run `dotnet iqsharp install` on line 15. The tool is already installed by the `iqsharp-base` image. You can see a example of a Dockerfile using `iqsharp-base` in our samples repo [here](https://github.com/microsoft/Quantum/blob/main/Dockerfile).

**Comment by anjbur** [comment] 2021-05-11 23:12
Let me know if you have any further questions! Closing in the meantime.

**Closed by anjbur** 2021-05-11 23:12 UTC
Labels: bug
