### ISSUE TITLE
Can run but with exception

### ISSUE THREAD

**Issue by sherlock666** [microsoft/iqsharp#76] opened 2019-12-30 04:14 UTC
Running
https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview

On Azure JupyterLab 
Only change ipynb to py for running

I can get the result correctly (see line 1)

but what are those exception means?
Is there any missing package?
Thanks!!

```
Hello from quantum world!
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f3c0319f2b8>>
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f3c0319f388>>
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f3c0319f1e8>>
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
```

**Comment by cgranade** [comment] 2019-12-30 18:45
Thanks for the report! This looks to be a duplicate of #39, so I'm going to close this to keep discussion localized there, but please feel free to re-open if this is a distinct issue. Thanks!

**Closed** 2019-12-30 18:45 UTC
Labels: bug, duplicate
