### ISSUE TITLE
I cannot install iqsharp.

### ISSUE THREAD

**Issue by MDHarmse15** [microsoft/iqsharp#65] opened 2019-11-18 20:53 UTC
I am using visual studio code (python) and have the necessary .NET installed (3.0) and I have installed the Quantum tool but when i get to the next line: dotnet iqsharp install, I obtain the following error:

Traceback (most recent call last):
  File "c:\users\michael m harmse\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\michael m harmse\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Michael M Harmse\AppData\Local\Programs\Python\Python37\Scripts\jupyter.exe\__main__.py", line 7, in <module>
  File "c:\users\michael m harmse\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "c:\users\michael m harmse\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-kernelspec` not found.

**Comment by cgranade** [comment] 2019-11-24 13:34
It looks like there's something wrong with your Jupyter setup that's causing `jupyter kernelspec` to not be available. That command is used by the IQ# installer to register itself as a kernel, similar to how IPython and other Jupyter kernels register themselves. To try and diagnose the problem, how did you install Jupyter? Thanks for the help!

**Comment by cgranade** [comment] 2019-12-03 17:52
As per offline discussion with @anpaz-msft, it sounds like this might be related to #63. That bug in turn is related to the upstream work at microsoft/jupyter-core#39, which should hopefully be included in released packages shortly.

**Comment by rmshaffer** [comment] 2020-04-20 22:54
This appears to be a duplicate of #112; at least the error message is the same. I'll close this as a duplicate for now. @MDHarmse15, if you are still having this problem, could you try the resolution described in that issue?

**Comment by rmshaffer** [comment] 2020-04-20 22:54
Duplicate of #112

**Closed by rmshaffer** 2020-04-20 22:54 UTC
Labels: Area-Install, bug
