### ISSUE TITLE
qsharp.azure.execute waits for 30 seconds, if results are not done, fails

### ISSUE THREAD

**Issue by guenp** [microsoft/iqsharp#406] opened 2021-01-28 18:11 UTC
**Describe the bug**
currently, when submitting a job to Azure Quantum using `qsharp.azure`, the client waits for 30 seconds and then throws an error if results are not returned.
since most jobs are going to take longer than 30 seconds, would it be an idea to not throw an error but just return immediately with a handle to the job ID? this gives the impression that something went wrong

**To Reproduce**
```
result = qsharp.azure.execute(RandomNumber, n=3, shots=1000, jobName="Generate 3-bit random number")
Waiting up to 30 seconds for Azure Quantum job to complete...
[10:03:28] Current job status: Waiting
[10:03:34] Current job status: Waiting
[10:03:39] Current job status: Waiting
[10:03:44] Current job status: Waiting
[10:03:49] Current job status: Waiting
Job ID fb4c07fb-d10e-497d-8eed-0f4de47909eb has not completed. To check the status, call %azure.status with the job ID.
---------------------------------------------------------------------------
AzureError                                Traceback (most recent call last)
<ipython-input-33-2bd34ae1e50b> in <module>
      1 qsharp.azure.target("honeywell.hqs-lt-1.0")
----> 2 result = qsharp.azure.execute(AllocateQubitsandApplyDriver, n=3, shots=1000, jobName="Generate 3-bit random number")
~/anaconda3/envs/releasetest/lib/python3.7/site-packages/qsharp/azure.py in execute(op, **params)
    135     """
    136     result = qsharp.client._execute_callable_magic("azure.execute", op, raise_on_stderr=False, **params)
--> 137     if "error_code" in result: raise AzureError(result)
    138     return result
    139 
AzureError: {'error_code': 1005, 'error_name': 'JobNotCompleted', 'error_description': 'The specified Azure Quantum job has not yet completed.'}
```

**Expected behavior**
Just wait until there is a result

**Comment by anjbur** [comment] 2021-05-27 23:03
Closing because this is the intended behavior. You can immediately get back the jobId by using `azure.submit`, or can pass a longer timeout value to `azure.execute`.

If you have more comments or input feel free to re-open the issue!

**Closed by anjbur** 2021-05-27 23:03 UTC
Labels: Area-Azure, bug
