### ISSUE TITLE
Python error: module 'qsharp' has no attribute 'clients'

### ISSUE THREAD

**Issue by sherlock666** [microsoft/iqsharp#75] opened 2019-12-26 13:18 UTC
Follow the operation guide and pip install qsharp 
(on Azure Machine Learning Studio  Python3 Notebook)
result in :

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-eeaf4e1dca22> in <module>
----> 1 import qsharp

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/qsharp/__init__.py in <module>
    117 ## STARTUP ##
    118 
--> 119 client = _start_client()
    120 packages = Packages(client)
    121 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/qsharp/clients/__init__.py in _start_client()
     22     if client_name == "iqsharp":
     23         import qsharp.clients.iqsharp
---> 24         client = qsharp.clients.iqsharp.IQSharpClient()
     25     elif client_name == "mock":
     26         import qsharp.clients.mock

AttributeError: module 'qsharp' has no attribute 'clients'
```
Not sure how to solve this problem

**Comment by cgranade** [comment] 2019-12-26 18:21
Thanks for reporting the issue! I've not seen this particular problem before, to try and diagnose it, would you be able to share how you installed IQ# in your Azure ML Studio environment? Thanks!

**Comment by sherlock666** [comment] 2019-12-30 04:15
@cgranade 

need to change ipynb to py on Azure ML Studio (JupyterLab)
Otherwise it may not get the file to import

**Comment by gines-carrascal** [comment] 2020-04-04 13:17
Same error in a fresh local install from jupyter notebook

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8772372fa121> in <module>
----> 1 import qsharp
      2 
      3 from qsharp import Result
      4 from Quantum.Bell import TestBellState
      5 

/opt/conda/lib/python3.7/site-packages/qsharp/__init__.py in <module>
    117 ## STARTUP ##
    118 
--> 119 client = _start_client()
    120 packages = Packages(client)
    121 

/opt/conda/lib/python3.7/site-packages/qsharp/clients/__init__.py in _start_client()
     22     if client_name == "iqsharp":
     23         import qsharp.clients.iqsharp
---> 24         client = qsharp.clients.iqsharp.IQSharpClient()
     25     elif client_name == "mock":
     26         import qsharp.clients.mock

AttributeError: module 'qsharp' has no attribute 'clients'
`

**Comment by rmshaffer** [comment] 2020-06-04 19:14
@gines-carrascal, if you are still experiencing this, could you share how you installed qsharp in your Python environment? This looks like an error where Python is unable to locate the `clients` folder inside your `qsharp` package, even though from your error trace, it is clearly seen to be there.

**Comment by rmshaffer** [comment] 2020-06-17 13:17
Closing this one since there doesn't seem to be anything actionable here, and it appears to be related to incomplete/corrupt installation of the Python package. If anyone hits this again and has steps to reproduce this issue, please comment here and/or open a new issue. Thanks!

**Closed by rmshaffer** 2020-06-17 13:17 UTC
Labels: Area-Python, bug
